### ISSUE TITLE
testcafe useRoles are broken on 4.0.1 and 4.1.0

### ISSUE THREAD

**Issue by andrewwood2** [testing-library/testcafe-testing-library#164] opened 2020-05-20 09:06 UTC
If I upgrade from 4.0.0 to either 4.0.1 or 4.1.0 then I get the following error from the testcafe (version 1.8.4) useRole feature:
```
An error occurred in a script injected into the tested page:
TypeError: Cannot read property 'destUrl' of null
```
I case it's helpful, my login function first goes to a logout address and then goes through the login steps.

**Comment by benmonro** [comment] 2020-05-20 12:26
Hi @andrewwood2  thanks for reporting this. Any chance you can provide a reproducible example?

**Comment by cbayer97** [comment] 2020-05-20 14:22
I got the same problem when upgrading from 4.0.0.
```
{ code: 'E64', isTestCafeError: true, callsite: CallsiteRecord { filename: '/someDir/runner.ts', lineNum: 58, callsiteFrameIdx: 6, stackFrames: [
      [CallSite], [CallSite],
      [CallSite], [CallSite],
      [CallSite], [CallSite],
      [CallSite], CallSite {},
      [CallSite], [CallSite],
      [CallSite]
      ], isV8Frames: true }, errMsg: "TypeError: Cannot read property 'destUrl' of null" }
```
The line pointed out actually performs `await t.navigateTo('http:/localhost:3000')`. I wasn't yet able to break it down to a reproducible example, but will look into that if I find the time.

**Comment by benmonro** [comment] 2020-05-20 15:35
thank you @cbayer97 or even if you have a code snippet that you can make generic enough to share here ,then I can attempt to reproduce it.

**Comment by benmonro** [comment] 2020-05-20 15:36
@Meemaw any ideas here?  This was caused by the typescript conversion...

**Comment by Meemaw** [comment] 2020-05-20 16:07
Typescript conversion should identically match prior behaviour, so that would be very surprising to me. An issue for this has already been opened https://github.com/DevExpress/testcafe/issues/5073

**Comment by benmonro** [comment] 2020-05-22 09:16
@andrewwood2  @cbayer97  can you look at the issue in testtcafe that @Meemaw  linked to?  The only other change between 4.0 and 4.1 was moving testcafe to peer dependencies so if there was a regression in testtcafe that might be the issue.

**Comment by benmonro** [comment] 2020-05-25 02:44
@cbayer97 @andrewwood2 any updates on this?

**Comment by benmonro** [comment] 2020-06-08 11:07
Closing but feel free to reopen if the corresponding issues in testtcafe is addressed

**Closed by benmonro** 2020-06-08 11:07 UTC
Labels: STATE: Need response, bug, help wanted, waiting for response
